<a href="https://colab.research.google.com/github/Gulayrose/DAwPy/blob/main/Assignment_1_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list = [5,10,15,20,25]
my_array = np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
b= np.ones((4,4),dtype="int")*7
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25, dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.16633004, 0.50355413, 0.31582908, 0.91152108, 0.04171114])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.rand(5,5) #/ np.random.randn(25).reshape(5,5)

array([[0.45636632, 0.7909204 , 0.938422  , 0.15817631, 0.03909048],
       [0.45297937, 0.40298853, 0.50632647, 0.7066052 , 0.61868861],
       [0.79405244, 0.80036502, 0.97576755, 0.05834196, 0.98703296],
       [0.07880289, 0.28025538, 0.00255307, 0.96102163, 0.91824409],
       [0.52364928, 0.20612236, 0.33694093, 0.47449682, 0.14641906]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50 , size=(3,4)) #/np.random.randint(20,50,12).reshape(3,4)

array([[41, 36, 21, 39],
       [23, 44, 48, 25],
       [38, 30, 35, 40]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(2,53,48)#/ranarr = np.random.randint(2,53, size = 48)
ranarr

array([ 7, 49, 38, 42, 16, 25, 41, 46, 12, 34, 35, 21, 40,  6, 18, 25, 48,
       31, 40, 32, 40, 35, 31, 31, 47, 38, 48,  2, 27, 15, 22, 32, 37, 48,
       44, 25, 11,  6, 22, 29, 17, 51, 50, 49,  7, 45, 16,  4])

In [ ]:
ranarr.reshape(6,8)

array([[ 7, 49, 38, 42, 16, 25, 41, 46],
       [12, 34, 35, 21, 40,  6, 18, 25],
       [48, 31, 40, 32, 40, 35, 31, 31],
       [47, 38, 48,  2, 27, 15, 22, 32],
       [37, 48, 44, 25, 11,  6, 22, 29],
       [17, 51, 50, 49,  7, 45, 16,  4]])

In [ ]:
#reshape with -1
ranarr.reshape(-1,8)#/ ranarr.reshape(6,-1)

array([[ 7, 49, 38, 42, 16, 25, 41, 46],
       [12, 34, 35, 21, 40,  6, 18, 25],
       [48, 31, 40, 32, 40, 35, 31, 31],
       [47, 38, 48,  2, 27, 15, 22, 32],
       [37, 48, 44, 25, 11,  6, 22, 29],
       [17, 51, 50, 49,  7, 45, 16,  4]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat[0:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat[1,::2]

array([5, 7])

In [ ]:
mat[2,[1,3]]

array([10, 12])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]] 

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
mat[1::2,::2]                   
      

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
x= mat[mat<10]
x

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
y = mat[mat>12]
y

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
x+y

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
np.std(x+y)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
list=mat[:,1].sum(axis=0)
list

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[2]

array([ 9, 10, 11, 12])

In [ ]:
v=mat[2]
v

array([ 9, 10, 11, 12])

In [ ]:
#median
np.median(v)

10.5

In [ ]:
#mean
np.mean(v)

10.5

In [ ]:
#std
np.std(v)

1.118033988749895

# Pandas Section

# New Section

In [ ]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [113]:
sal=pd.read_csv('Salaries.csv')

In [114]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [115]:
sal.describe()

Id        BasePay    OvertimePay  ...          Year  Notes  Status
count  59233.000000   59232.000000   59232.000000  ...  59232.000000    0.0     0.0
mean   29617.000000   74017.174481    5725.170210  ...   2011.389536    NaN     NaN
std    17099.238584   39091.698816   11952.691712  ...      0.487649    NaN     NaN
min        1.000000       0.000000       0.000000  ...   2011.000000    NaN     NaN
25%    14809.000000   53728.990000       0.000000  ...   2011.000000    NaN     NaN
50%    29617.000000   71610.580000     133.760000  ...   2011.000000    NaN     NaN
75%    44425.000000  100604.100000    6162.625000  ...   2012.000000    NaN     NaN
max    59233.000000  302578.000000  245131.880000  ...   2012.000000    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [116]:
sal.Year.value_counts()

2011.0    36159
2012.0    23073
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [117]:
#max
sal.TotalPay.max()

567595.43

In [118]:
#avg
sal.TotalPay.mean()

83942.5083405976

**How many records are there which have TotalPay bigger than avg TotalPay**

In [119]:
len(sal.TotalPay[sal.TotalPay > sal.TotalPay.mean()].value_counts())

25509

**How much does ALBERT PARDINI make (including benefits)?**

In [120]:
sal.TotalPayBenefits[sal["EmployeeName"]== "ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [121]:
sal[sal.TotalPayBenefits== sal.TotalPayBenefits.min()]["EmployeeName"]

36156        PAULETTE ADAMS
36157         KAUKAB MOHSIN
36158    JOSEPHINE MCCREARY
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [122]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Shade and Drapery Worker', 'Sr Materials & Supplies Sprv', nan],
      dtype=object)

**List 3 least common Jobs**

In [123]:
sal["JobTitle"].value_counts().sort_values()[0:3]

SENIOR CLAIMS INVESTIGATOR             1
SHELTER OFFICE ASSISTANT SUPERVISOR    1
Sup Ct Admin Secretary                 1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [124]:
sal[(sal.TotalPayBenefits>sal.TotalPayBenefits.mean()) & (sal.Year==2012)]["EmployeeName"].count()

19330

**How many people have the word Manager in their job title?**

In [133]:
def manager_func(x):
    if 'manager' in x.lower():
        return True
    else:
        return False

In [ ]:
len(sal[sal.JobTitle.apply(lambda x:manager_func(x))])

In [ ]:
len(salary[salary.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [135]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [136]:
sal_new=sal.iloc[:,[0,1,2,7,8]]
sal_new.head()

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0   1     NATHANIEL FORD  ...  567595.43         567595.43
1   2       GARY JIMENEZ  ...  538909.28         538909.28
2   3     ALBERT PARDINI  ...  335279.91         335279.91
3   4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4   5    PATRICK GARDNER  ...  326373.19         326373.19

[5 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [137]:

sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0          1     NATHANIEL FORD  ...  567595.43         567595.43
1          2       GARY JIMENEZ  ...  538909.28         538909.28
2          3     ALBERT PARDINI  ...  335279.91         335279.91
3          4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4          5    PATRICK GARDNER  ...  326373.19         326373.19
...      ...                ...  ...        ...               ...
59228  59229       Gwen Brister  ...   57439.54          84694.76
59229  59230    Shawn Sherburne  ...   58734.01          84689.54
59230  59231         George Toy  ...   56980.73          84685.62
59231  59232         Henry Wong  ...   56525.00          84685.25
59232  59233               Dian  ...        NaN               NaN

[59233 rows x 5 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [138]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]["EmployeeName"]

9847     EKERETTE ESSIEN
9848           JEAN LELU
9849         RICK BURGER
9850        ERIC SHAFFER
9851       LEO BERNSTEIN
              ...       
59227          Robert Wu
59228       Gwen Brister
59229    Shawn Sherburne
59230         George Toy
59231         Henry Wong
Name: EmployeeName, Length: 30052, dtype: object

In [139]:
salary_less_average = sal[(sal.TotalPayBenefits)<(sal.TotalPayBenefits.mean()) ]
salary_less_average.EmployeeName.iloc[:-1]

9847     EKERETTE ESSIEN
9848           JEAN LELU
9849         RICK BURGER
9850        ERIC SHAFFER
9851       LEO BERNSTEIN
              ...       
59226       Erin Gadbois
59227          Robert Wu
59228       Gwen Brister
59229    Shawn Sherburne
59230         George Toy
Name: EmployeeName, Length: 30054, dtype: object