<a href="https://colab.research.google.com/github/Gulayrose/DAwPy/blob/main/DAwPy_S3_(Pandas_Series)_empty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import pandas as pd
import numpy as np

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr

array([10, 20, 30])

In [8]:
pd.Series(data=arr,index=labels)#numpy dan ne buyuk farki kendimiz index verebiliyruz

a    10
b    20
c    30
dtype: int64

### **Using Dictionary**

In [9]:
d

{'a': 10, 'b': 20, 'c': 30}

In [10]:
pd.Series(d) # burda key ler index tir 

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d,index=["q","c","y"]) # biz burda index vermeye kalkarsak
#ustte verdigimizi cikartir.ama eger yukardaki ile eslesmezse nan atar

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [12]:
pd.Series(data="Ahmet")

0    Ahmet
dtype: object

In [13]:
pd.Series(data="Ahmet",index=range(1,5))

1    Ahmet
2    Ahmet
3    Ahmet
4    Ahmet
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

In [14]:
set1 = (1,2,3,6)

In [15]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [17]:
pd.Series([set,list,dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [18]:
pd.Series([set,list,dict])[0]([2,5,7,8,2])

{2, 5, 7, 8}

In [30]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In [19]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [20]:
pd.Series([sum,print,len])[0]([3,5,7])

15

In [21]:
mix_data = ['Aziz', 2, True]

In [23]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [24]:
ser.dtype # ser in type object

dtype('O')

In [25]:
type(ser)

pandas.core.series.Series

In [26]:
type(ser[0])# diger indexler icinde bakilabilir

str

In [27]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [28]:
type(arr[0])

numpy.str_

In [29]:
type(arr[1])

numpy.str_

burda seri de icindeki elemanlarin tipini korurken arr de korumadi hepsini str olarak cikartti

### Basic Attributes of Series

In [33]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    97
1    87
2    28
3    74
4    19
5    51
6    94
dtype: int64

In [34]:
ser.dtype

dtype('int64')

In [35]:
type(ser)

pandas.core.series.Series

In [36]:
ser.shape # row sayisini verir

(7,)

In [37]:
ser.size# tek dimension oldugu icin size ve shape ve len ayni vermeli

7

In [38]:
len(ser)

7

In [39]:
ser.ndim # 1 boyutlu oldugu icin 1 cikar

1

In [40]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [41]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [42]:
for i in ser.index:
  print(i)

0
1
2
3
4
5
6


In [44]:
ser.keys() # burda indexlere ulasabiliriz eger() kullanamazsak degerleri goruruz

RangeIndex(start=0, stop=7, step=1)

In [47]:
ser.keys

<bound method Series.keys of 0    97
1    87
2    28
3    74
4    19
5    51
6    94
dtype: int64>

In [45]:
ser.values

array([97, 87, 28, 74, 19, 51, 94])

In [50]:
ser.items()

In [51]:
list(ser.items())

[(0, 97), (1, 87), (2, 28), (3, 74), (4, 19), (5, 51), (6, 94)]

In [52]:
for index,value in ser.items():
  print(f"index:{index},value:{value}")

index:0,value:97
index:1,value:87
index:2,value:28
index:3,value:74
index:4,value:19
index:5,value:51
index:6,value:94


In [54]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c    19
b    18
a     1
e    21
f     9
d    19
g    24
i     6
h     9
j    10
dtype: int64

In [55]:
ser.head() #ilk 5 i gosterir.yada icine biryer yazarsak bastan o kadar gosterir;

c    19
b    18
a     1
e    21
f     9
dtype: int64

In [56]:
ser.tail()#sondan 5 i gosterir.

d    19
g    24
i     6
h     9
j    10
dtype: int64

In [57]:
ser.sample() #datanin herhangi bir yerinden sample getirir.icine yine baska sayilar yazabiliriz

h    9
dtype: int64

In [58]:
ser.sort_index(ascending=True) # index i alphabetic siraladi

a     1
b    18
c    19
d    19
e    21
f     9
g    24
h     9
i     6
j    10
dtype: int64

In [59]:
ser.sort_values(ascending=True)# value ya gore siralar 

a     1
i     6
f     9
h     9
j    10
b    18
c    19
d    19
e    21
g    24
dtype: int64

In [60]:
ser

c    19
b    18
a     1
e    21
f     9
d    19
g    24
i     6
h     9
j    10
dtype: int64

In [61]:
ser.isin([5,9])#benim liste icinde 5 ve 9 um var mi bool dondurur.

c    False
b    False
a    False
e    False
f     True
d    False
g    False
i    False
h     True
j    False
dtype: bool

In [62]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [63]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [64]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [65]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [66]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [67]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [68]:
ser1[1] # bize burda value lari dondurur.

2

In [69]:
ser1["Germany"] # yada index in sahip oldugu value da bulabiliriz

2

In [70]:
ser1.Germany # co tavsiye edilen bir method degildir.ve sadeec str yazilabilir.

2

In [71]:
ser1+ ser2 # index i ayni olanlarin value larini topladi.olmayani nan yazdi

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

Operations are then also done based off of index:

In [73]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [72]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [74]:
ser3[0]

'a'

In [75]:
ser3[:2]

0    a
1    b
dtype: object

In [76]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [77]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [78]:
panser[["terry", "orion"]]

terry    121
orion    150
dtype: int64

In [79]:
panser["terry" : "orion"] # burda ikisinide alir 

terry      121
micheal    200
orion      150
dtype: int64

In [80]:
panser[0:3] #burda son olani almaz 

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes an some attributes

*   List item
*   List item



In [81]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [83]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [84]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [85]:
panser.values

array([121, 200, 150,  99])

In [86]:
panser.items()

In [87]:
for index, value in panser.items():
  print(index,value)

terry 121
micheal 200
orion 150
jason 99


In [88]:
"terry" in panser 

True

In [89]:
"bon" in panser

False

In [91]:
121 in panser.values

True

In [92]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [93]:
panser["terry"] = 90
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [94]:
panser[panser>100]

micheal    200
orion      150
dtype: int64

In [96]:
panser[panser>100] = 75
panser

terry      90
micheal    75
orion      75
jason      99
dtype: int64