<a href="https://colab.research.google.com/github/Gulayrose/DAwPy/blob/main/free_working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mat=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
mate= np.arange(1,17).reshape(4,4)
mate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
mat[2]

array([ 9, 10, 11, 12])

In [36]:
np.mean(mat[2])

10.5

In [37]:
np.median(mat[2])

10.5

In [38]:
np.std(mat[2])

1.118033988749895

In [40]:
import pandas as pd

In [41]:
sal = pd.read_csv("Salaries.csv")

In [43]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]