<a href="https://colab.research.google.com/github/Gulayrose/DAwPy/blob/main/np_mentorluk_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.33441334])

In [26]:
np.random.randn(25) # standart normal distribution

array([-0.65023141, -1.13906802, -1.86222989, -0.28029276,  1.39868029,
       -0.62289592, -0.70743645, -0.68525973, -0.35094125,  0.36177587,
        0.48577109,  0.05722994, -0.71353736, -0.45109356,  0.12071611,
       -0.69268295,  0.19424826, -0.65825009, -0.55636764, -1.12876763,
       -0.05122062, -0.21685219, -0.72043142,  0.60125456, -1.06168368])

In [30]:
np.random.randn(10,10).round(2) # virgulden sonra 2 basaamkli 

array([[-0.4 , -0.29,  0.6 ,  1.26,  1.26, -1.03,  0.24,  0.95, -0.04,
        -1.29],
       [-0.31,  1.19, -0.84, -0.51,  0.11, -1.51,  0.21, -0.6 ,  0.16,
        -0.12],
       [ 0.6 , -0.31,  0.87, -0.72,  0.54, -0.33,  0.56,  0.2 ,  0.02,
        -1.32],
       [-0.6 , -0.42, -0.26,  2.56,  0.04, -0.24, -1.67, -0.96, -0.45,
        -0.38],
       [-1.65,  0.25, -0.05, -0.4 , -0.08, -2.23,  1.65,  0.6 ,  1.24,
         0.94],
       [ 1.65,  1.84,  1.29,  2.34, -0.94,  0.48, -1.44, -1.11, -1.45,
         0.41],
       [ 2.  ,  0.57,  0.55, -0.85, -0.52, -0.18,  1.37,  0.58, -0.75,
         1.49],
       [ 0.6 ,  0.63,  1.32, -0.4 , -0.08, -0.32,  0.16, -1.22, -0.9 ,
        -0.42],
       [-0.7 , -1.49,  0.28,  0.69,  0.11,  0.45, -0.12, -1.07, -0.66,
        -0.64],
       [-0.37,  0.77, -0.11, -0.47, -0.22,  2.62, -0.56,  1.02, -0.92,
        -1.92]])

In [31]:
np.random.randn(4,5) # pozitif donmesi icin ne gerekiyordu??

array([[ 0.47808916,  0.61783832, -0.66801194, -0.64140401, -2.15029208],
       [ 0.93672565, -0.18486285, -0.34676015, -0.19571438,  0.30783842],
       [-0.71960204, -1.32749347, -2.24914067,  0.8024258 ,  0.62335354],
       [ 0.20762715, -1.28021944, -0.36420601,  0.33812192,  0.43706222]])

In [32]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
mat[3,4]

20

In [35]:
mat[[0,1,2],[1,1,1]]

array([ 2,  7, 12])

In [41]:
mat[[0,1,2],1] # [[2],[7],[12]] olmasi gerek ti nasil olacak ?

array([ 2,  7, 12])

In [43]:
mat[4]

array([21, 22, 23, 24, 25])

In [44]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
mat[:,:].sum() # sum of whole values

325

In [46]:
mat[:,:].std()# std of whole values

7.211102550927978

In [ ]:
#sadece coloumn larin toplami?? [55,60,65,70,75]